spring:
  datasource:
    username: root
    password: root
#    url: jdbc:p6spy:mysql://localhost:3306/oauth_resource_project?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/lrc_short_chain?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
