server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  freemarker:
    suffix: .html
  profiles:
    active: dev


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: is_del
      where-strategy: not_empty
      update-strategy: not_empty
      insertStrategy: not_empty