server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root
    url: jdbc:p6spy:mysql://localhost:3306/oauth_resource_project?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  freemarker:
    suffix: .html
  profiles:
    active: dev