server:
  port: 8888

spring:
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .html
  profiles:
    active: dev